### ISSUE TITLE
Add support for SDI

### ISSUE THREAD

**Issue by sfahadshahzad** [Eyevinn/tsgen-svc#23]
Hi Birme,

It would be very helpful if you can add support in api to get decklink sdi video source port to generate mpegts from live input.

Thanks

Fahad

**Comment by svensson00** [comment]
Hi Fahad,

If I understand correctly you basically need an encoder that takes decklink sdi video input and generate mpeg-ts output. This is not exactly the purpose of the tsgen component that is more to generate an mpeg-ts test stream to avoid the need for an encoder.

But we could as a consultancy service help you build a new component according to your needs. Let me know if this is interesting and we could have a separate discussion.

Magnus
